name: Mirror to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to personal repo
        run: |
          git remote add mirror https://rskaindoy:${{ secrets.PERSONAL_PUSH_TOKEN }}@github.com/rskaindoy/UPV-PAWtrol-Deploy.git
          git push --force mirror main